#!/usr/bin/env bash
#
# deploy.sh - build and deploy the Digital Hub Knowledge & Collaboration Platform.
#
# Idempotent. Exits non-zero on failure. Writes outputs.json (including app_url)
# at the repo root on success. Run by the platform's build system.
#
# Order of operations (see CLAUDE.md):
#   1. Ensure the deploy-artifacts S3 bucket exists (never use --resolve-s3).
#   2. Ensure the S3 Vectors bucket + one index per entity exist (CLI, not CFN -
#      the same "not a CloudFormation resource" pattern the contract uses for ECR).
#   3. npm install (so any later `npm ci` has a fresh lockfile), then sam build.
#   4. sam deploy into the app-193a359c-027ffd1c-portal stack.
#   5. Generate frontend/config.js from stack outputs, upload the SPA, invalidate
#      CloudFront, and write outputs.json.

set -euo pipefail

REGION="ap-southeast-1"
PREFIX="app-193a359c-027ffd1c-"
STACK="${PREFIX}portal"
ARTIFACTS_BUCKET="${PREFIX}artifacts"
VECTOR_BUCKET="${PREFIX}vectors"
ENTITIES="problems initiatives solutions findings assets sme-profiles"
EMBED_DIM="1024"

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

log() { echo "[deploy] $*"; }

# ---------------------------------------------------------------------------
# 1. Deploy-artifacts bucket
# ---------------------------------------------------------------------------
log "Ensuring artifacts bucket ${ARTIFACTS_BUCKET} exists"
if ! aws s3api head-bucket --bucket "$ARTIFACTS_BUCKET" 2>/dev/null; then
  aws s3api create-bucket \
    --bucket "$ARTIFACTS_BUCKET" \
    --region "$REGION" \
    --create-bucket-configuration LocationConstraint="$REGION"
  aws s3api put-bucket-encryption \
    --bucket "$ARTIFACTS_BUCKET" \
    --server-side-encryption-configuration \
      '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}' || true
fi

# ---------------------------------------------------------------------------
# 2. S3 Vectors bucket + per-entity indexes (idempotent, via the s3vectors CLI)
# ---------------------------------------------------------------------------
log "Ensuring S3 Vectors bucket ${VECTOR_BUCKET} exists"
if ! aws s3vectors get-vector-bucket --vector-bucket-name "$VECTOR_BUCKET" --region "$REGION" >/dev/null 2>&1; then
  aws s3vectors create-vector-bucket --vector-bucket-name "$VECTOR_BUCKET" --region "$REGION"
fi

for ENTITY in $ENTITIES; do
  if ! aws s3vectors get-index --vector-bucket-name "$VECTOR_BUCKET" --index-name "$ENTITY" --region "$REGION" >/dev/null 2>&1; then
    log "Creating vector index ${ENTITY}"
    aws s3vectors create-index \
      --vector-bucket-name "$VECTOR_BUCKET" \
      --index-name "$ENTITY" \
      --data-type float32 \
      --dimension "$EMBED_DIM" \
      --distance-metric cosine \
      --metadata-configuration '{"nonFilterableMetadataKeys":["snippet"]}' \
      --region "$REGION"
  fi
done

# ---------------------------------------------------------------------------
# 3. Install dependencies (fresh lockfiles) then build
# ---------------------------------------------------------------------------
log "Installing layer + function dependencies"
( cd layer && npm install --no-audit --no-fund )
( cd src && npm install --no-audit --no-fund )

log "sam build"
sam build --region "$REGION"

# ---------------------------------------------------------------------------
# 4. Deploy the CloudFormation/SAM stack
# ---------------------------------------------------------------------------
log "sam deploy -> ${STACK}"
sam deploy \
  --stack-name "$STACK" \
  --s3-bucket "$ARTIFACTS_BUCKET" \
  --s3-prefix "$STACK" \
  --region "$REGION" \
  --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
  --no-confirm-changeset \
  --no-fail-on-empty-changeset \
  --no-progressbar

# ---------------------------------------------------------------------------
# 5. Post-deploy: config.js, SPA upload, CloudFront invalidation, outputs.json
# ---------------------------------------------------------------------------
log "Reading stack outputs"
OUTPUTS_JSON="$(aws cloudformation describe-stacks --stack-name "$STACK" --region "$REGION" --query 'Stacks[0].Outputs' --output json)"

out() { echo "$OUTPUTS_JSON" | jq -r --arg k "$1" '(.[] | select(.OutputKey==$k) | .OutputValue) // ""'; }

APP_URL="$(out AppUrl)"
API_URL="$(out ApiUrl)"
WEBHOOK_API_URL="$(out WebhookApiUrl)"
USER_POOL_ID="$(out UserPoolId)"
USER_POOL_CLIENT_ID="$(out UserPoolClientId)"
COGNITO_DOMAIN="$(out CognitoDomain)"
SPA_BUCKET="$(out SpaBucketName)"
DISTRIBUTION_ID="$(out DistributionId)"

log "Generating frontend/config.js"
cat > frontend/config.js <<EOF
// Generated by deploy.sh - do not edit or commit.
window.APP_CONFIG = {
  apiUrl: "${API_URL}",
  region: "${REGION}",
  userPoolId: "${USER_POOL_ID}",
  userPoolClientId: "${USER_POOL_CLIENT_ID}",
  cognitoDomain: "${COGNITO_DOMAIN}"
};
EOF

if [ -n "$SPA_BUCKET" ]; then
  log "Uploading SPA to s3://${SPA_BUCKET}"
  aws s3 sync frontend/ "s3://${SPA_BUCKET}/" --delete --region "$REGION"
fi

if [ -n "$DISTRIBUTION_ID" ]; then
  log "Invalidating CloudFront distribution ${DISTRIBUTION_ID}"
  aws cloudfront create-invalidation --distribution-id "$DISTRIBUTION_ID" --paths '/*' >/dev/null || true
fi

log "Writing outputs.json"
jq -n \
  --arg app_url "$APP_URL" \
  --arg api_url "$API_URL" \
  --arg webhook_api_url "$WEBHOOK_API_URL" \
  --arg user_pool_id "$USER_POOL_ID" \
  --arg user_pool_client_id "$USER_POOL_CLIENT_ID" \
  --arg cognito_domain "$COGNITO_DOMAIN" \
  --arg spa_bucket "$SPA_BUCKET" \
  --arg distribution_id "$DISTRIBUTION_ID" \
  --arg region "$REGION" \
  '{app_url:$app_url, api_url:$api_url, webhook_api_url:$webhook_api_url, user_pool_id:$user_pool_id, user_pool_client_id:$user_pool_client_id, cognito_domain:$cognito_domain, spa_bucket:$spa_bucket, distribution_id:$distribution_id, region:$region}' \
  > outputs.json

log "Done. app_url = ${APP_URL}"
